version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  db:
    image: mysql:8.0
    environment:
      # estas deberias ser variables de entorno para no tener que manipular este archivo en caso de requerir cambios
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: challenge
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
